extends = "../ftgs/dance1.toml"

[init]
temporal_motion_adapted = true
temporal_flow_path = "_flow/selfcap/dance1"
temporal_covis_thresh = 0.7

[train]
color_correction = true
color_correction_start = 15000
color_corrector_weight = 5e-2

[model]
max_duration = 1
marginal_gating = true
