#!/usr/bin/env bash

set -euxo pipefail

scenes="coffee_martini cook_spinach cut_roasted_beef flame_salmon flame_steak sear_steak"
runpath="_run/dynerf"

for scene in $scenes
do
  cfg="configs/dynerf/ftgs/$scene.toml"
  out="$runpath/$scene"

  uv run -m ftgspp.data.extract $cfg
  uv run -m ftgspp.data.sfm $cfg
  uv run -m ftgspp.data.prep $cfg
  uv run -m ftgspp.init.points $cfg
  uv run -m ftgspp.init $cfg $out
  uv run -m ftgspp.train $cfg $out

  uv run -m ftgspp.eval   $out $out/metrics.json
  uv run -m ftgspp.render $out $out/rgb.mp4 --camera 0
  uv run -m ftgspp.render $out $out/errmap.mp4 --mode error-map --camera 0
  uv run -m ftgspp.render $out $out/vfield.mp4 --mode velocity-field --camera 0
done

jq -n '
  (reduce inputs as $file ({}; . + {($file | input_filename | split("/")[-2]): $file})) as $perscene |
  ($perscene | map(to_entries) | transpose | map({(.[0].key): (map(.value) | add / length)}) | add) as $mean |
  $perscene + {mean: $mean}' \
  $runpath/*/metrics.json > $runpath/metrics.json
